#!/usr/bin/env bash
# pr_gate.sh - auto-approve or flag PRs based on review report
# Usage: ./scripts/pr_gate.sh <PR_NUMBER> [owner/repo]
# Required env vars: GITHUB_TOKEN
# Reads /tmp/pr_review_<PR>.txt (output of pr_review.sh)
set -euo pipefail

PR_NUMBER="${1:-}"
REPO="${2:-}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ -z "$PR_NUMBER" ]]; then
  echo "Usage: $0 <PR_NUMBER> [owner/repo]"
  exit 1
fi

if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  echo "ERROR: GITHUB_TOKEN is not set. Export it before running."
  exit 1
fi

if [[ -z "$REPO" ]]; then
  REPO=$(git remote get-url origin 2>/dev/null | sed -E "s|.*github\.com[:/]||;s|\.git$||") || true
fi
if [[ -z "$REPO" ]]; then
  echo "ERROR: Could not detect repo."
  exit 1
fi

REPORT_FILE="/tmp/pr_review_${PR_NUMBER}.txt"

# Run pr_review.sh if report does not exist
if [[ ! -f "$REPORT_FILE" ]]; then
  echo "Running pr_review.sh first..."
  "${SCRIPT_DIR}/pr_review.sh" "$PR_NUMBER" "$REPO" || true
fi

if [[ ! -f "$REPORT_FILE" ]]; then
  echo "ERROR: Review report not found at $REPORT_FILE"
  exit 1
fi

FAIL_COUNT=$(grep -c "^FAIL:" "$REPORT_FILE" 2>/dev/null || echo 0)
WARN_COUNT=$(grep -c "^WARN:" "$REPORT_FILE" 2>/dev/null || echo 0)
PASS_COUNT=$(grep -c "^PASS:" "$REPORT_FILE" 2>/dev/null || echo 0)

echo "Gate decision for PR #${PR_NUMBER}"
echo "  PASS: $PASS_COUNT  WARN: $WARN_COUNT  FAIL: $FAIL_COUNT"

# Format review body
REPORT_BODY=$(cat "$REPORT_FILE")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [[ "$FAIL_COUNT" -gt 0 ]]; then
  DECISION="REQUEST_CHANGES"
  SUMMARY="PR Gate: $FAIL_COUNT issue(s) require attention before merge."
  echo "DECISION: REQUEST_CHANGES (hard failures found)"
elif [[ "$WARN_COUNT" -gt 2 ]]; then
  DECISION="COMMENT"
  SUMMARY="PR Gate: $WARN_COUNT warnings detected. Review recommended."
  echo "DECISION: COMMENT (multiple warnings)"
else
  DECISION="APPROVE"
  SUMMARY="PR Gate: All checks passed ($PASS_COUNT pass, $WARN_COUNT warn)."
  echo "DECISION: APPROVE"
fi

# Build comment body
COMMENT="### PR Gate Report

${SUMMARY}

\`\`\`
${REPORT_BODY}
\`\`\`

*Generated by pr_gate.sh at ${TIMESTAMP}*"

# Post review via GitHub API
ENCODED_BODY=$(python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))" <<< "$COMMENT")

API_URL="https://api.github.com/repos/${REPO}/pulls/${PR_NUMBER}/reviews"
HTTP_STATUS=$(curl -s -o /tmp/pr_gate_response.json -w "%{http_code}" \
  -X POST "$API_URL" \
  -H "Authorization: token ${GITHUB_TOKEN}" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  -d "{"body": ${ENCODED_BODY}, "event": "${DECISION}"}")

if [[ "$HTTP_STATUS" == "200" || "$HTTP_STATUS" == "201" ]]; then
  echo "Review posted successfully (HTTP $HTTP_STATUS)"
else
  echo "WARN: Review post returned HTTP $HTTP_STATUS"
  cat /tmp/pr_gate_response.json 2>/dev/null || true
fi

# Exit non-zero if request_changes
if [[ "$DECISION" == "REQUEST_CHANGES" ]]; then
  exit 2
fi
